### ISSUE TITLE
Lucene dependency - issue with 4.6.1

### ISSUE THREAD

**Issue by dglachs** [wikier/marmotta-search#1]
```
12:34:30.475 ERROR - null:java.lang.NoClassDefFoundError: org/apache/lucene/codecs/lucene45/Lucene45DocValuesConsumer
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2472)
    at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:854)
    at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1274)
    at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1157)
    at java.lang.Class.getDeclaredConstructors0(Native Method)
    at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
    at java.lang.Class.getConstructor0(Class.java:3075)
    at java.lang.Class.newInstance(Class.java:412)
    at org.apache.lucene.util.NamedSPILoader.reload(NamedSPILoader.java:67)
    at org.apache.lucene.util.NamedSPILoader.<init>(NamedSPILoader.java:47)
    at org.apache.lucene.util.NamedSPILoader.<init>(NamedSPILoader.java:37)
    at org.apache.lucene.codecs.DocValuesFormat.<clinit>(DocValuesFormat.java:43)
    at org.apache.solr.core.SolrResourceLoader.reloadLuceneSPI(SolrResourceLoader.java:185)
    at org.apache.solr.core.SolrResourceLoader.<init>(SolrResourceLoader.java:122)
    at org.apache.solr.core.SolrResourceLoader.<init>(SolrResourceLoader.java:236)
    at org.apache.solr.servlet.SolrDispatchFilter.createCoreContainer(SolrDispatchFilter.java:180)
    at org.apache.solr.servlet.SolrDispatchFilter.init(SolrDispatchFilter.java:133)
    at at.newmedialab.lmf.search.filters.LMFSearchFilter.init(LMFSearchFilter.java:145)
    at at.newmedialab.lmf.search.filters.LMFSearchFilter$Proxy$_$$_WeldClientProxy.init(Unknown Source)
    at org.apache.marmotta.platform.core.servlet.MarmottaResourceFilter.init(MarmottaResourceFilter.java:90)
    at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:279)
    at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:260)
    at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:105)
    at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4573)
    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5192)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
    at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1409)
    at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1399)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.apache.lucene.codecs.lucene45.Lucene45DocValuesConsumer
    at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1305)
    at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1157)
    ... 35 more
```

marmotta search uses lmf-util which has a dependency on "lucene 4.3.0"

**Comment by wikier** [comment]
we need to check this commit https://github.com/wikier/marmotta-search/commit/fa5a1902dbd587465f8b6c64022354c014118709
